$(function(){
	$('#login').dialog({
		title:'登录后台',
		width:300,
		height:180,
		modal:true,
		iconCls:'icon-lock',
		buttons:'#btn',
	});
	//管理员账号验证
	$('#manager').validatebox({
		required:true,
		missingMessage:'请输入管理员账号',
		invalidMessage:'管理员账号不能为空',
	});
	//管理员密码验证
	$('#password').validatebox({
		required:true,
		validType:'length[6,30]',
		missingMessage:'请输入管理员密码',
		invalidMessage:'管理员密码不能为空',
	});
	//加载时判断验证
	if(!$('#manager').validatebox('isValid')){
		$('#manager').focus();
	}else if(!$('#password').validatebox('isValid')){
		$('#password').focus();
	}
	
	//单击登录
	$('#btn a').click(function(){
		if(!$('#manager').validatebox('isValid')){
			$('#manager').focus();
		}else if(!$('#password').validatebox('isValid')){
			$('#password').focus();
		}else{
			$.ajax({
				url:'CheckLogin.do',
				type:'post',
				data:{
					manager:$('#manager').val(),
					password:$('#password').val(),
				},
				beforeSend:function(){
					$.messager.progress({
						text:"正在登录中...",
					});
				},
				success:function(data,response,status){
					$.messager.progress('close');
					if(data>0){
						location.href='index.jsp';
					}else{
						$.messager.alert('登录失败','用户名或密码错误！','warning',function(){
							$('#password').select();
						});
					}
				},
			});
		}
	});
	
});